#! /usr/bin/env bash

UNAME="silence"
REMOTE="$astral"
LOCAL_DIR="$foundry"
REMOTE_DIR="/mnt/SIGIL/2_Foundry/Data/0_CUSTOM/"

# Stop docker container
echo -e "\n\033[1mStopping docker container on remote server...\033[0m"
ssh "$UNAME"@"$REMOTE" -t sudo docker stop Foundry
sleep 3

# Transfer data
echo -e "\n\033[1mStarting rysnc transfer to remote directory\033[0m"
rsync -avh "$LOCAL_DIR" "$UNAME"@"$REMOTE":"$REMOTE_DIR" --delete-after
sleep 3

# restart docker container
echo -e "\n\033[1mrestarting docker container on remote server...\033[0m"
ssh "$UNAME"@"$REMOTE" -t sudo docker restart Foundry
echo -e "\n\033[1mDone ヽ(´ー｀)ノ\033[0m\n"
